#!/bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
source lib/functions.sh

load_config
verify_ca

if [ $# -lt 1 ]; then
  echo "usage: $0 example.com [www.example.com] [*.example.com]"
  echo "   - This will sign a request generated by 'request-generate.sh'"
  echo "   - To sign a request generated somewhere else, save it as"
  echo "       $DATA/<common name>/<common name>.csr"

  exit 1;
fi
CN="$1"; shift

generate_usrcert_config $@
generate_openssl_config

openssl ca -batch -config "$DATA/generated.cnf" -out "$DATA/$CN/$CN.crt" -infiles "$DATA/$CN/$CN.csr"
rm -f "$USR_CERT"

if [ ! -e "$DATA/$CN/$CN.crt" ]; then
  print_error "Unable to create a certificate for $CN"
  exit 1
else
  print_info "Signed a certificate with the filename '$DATA/$CN/$CN.crt'"
fi
